import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import SEO from '@/components/layout/SEO'
import VerseCard from '@/components/ui/VerseCard'
import StoryCard from '@/components/ui/StoryCard'
import Icon, { type IconName } from '@/components/ui/Icon'
import { VerseCardSkeleton, StoryCardSkeleton } from '@/components/ui/Skeleton'
import { fetchDailyContent, todayStr } from '@/utils/dateUtils'
import { websiteSchema, dailyVerseSchema } from '@/utils/structuredData'
import { fetchDailyBackgroundUri } from '@/utils/lazyBackground'
import type { DailyContent, Story } from '@/types'

const SITE_URL = import.meta.env.VITE_SITE_URL ?? 'https://ravin7990.github.io/daily-bible-verse'
const BASE = import.meta.env.BASE_URL || '/'

interface FeaturedWallpaper {
  id: string
  title: string
  category: string
  url: string
}

export default function Home() {
  const [content, setContent]               = useState<DailyContent | null>(null)
  const [loading, setLoading]               = useState(true)
  const [featuredStories, setFeatured]      = useState<Story[]>([])
  const [storiesLoading, setStoriesLoading] = useState(true)
  const [heroBgUrl, setHeroBgUrl]           = useState<string>(`${BASE}images/daily_hero_bg.webp`)
  const [lightboxImage, setLightboxImage]   = useState<string | null>(null)
  const [copied, setCopied]                 = useState(false)
  const [isPlaying, setIsPlaying]           = useState(false)

  const today = todayStr()

  /* Lightbox: Escape closes it and the page behind it must not scroll. */
  useEffect(() => {
    if (!lightboxImage) return

    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setLightboxImage(null)
    }
    const prevOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    document.addEventListener('keydown', onKeyDown)

    return () => {
      document.body.style.overflow = prevOverflow
      document.removeEventListener('keydown', onKeyDown)
    }
  }, [lightboxImage])

  useEffect(() => {
    fetchDailyContent(today).then((data: DailyContent | null) => {
      setContent(data)
      setLoading(false)
    })

    // Fetch dynamic date-based background if available from Firebase Storage
    fetchDailyBackgroundUri(today).then(url => {
      if (url) setHeroBgUrl(url)
    })

    // Only the fields StoryCard renders. The full stories.json is ~920 kB
    // because each entry embeds the entire story body; fetching that to show
    // six cards was the heaviest request on the home page.
    // stories-featured.json is ~2 kB and is generated by scripts/generate-assets.js.
    fetch(`${BASE}stories-featured.json`)
      .then(r => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`)
        return r.json()
      })
      .then((data: Story[]) => {
        setFeatured(data)
        setStoriesLoading(false)
      })
      .catch(() => setStoriesLoading(false))
  }, [today])

  function handleCopy() {
    if (!content) return
    const text = `"${content.verse_of_the_day.text}" — ${content.verse_of_the_day.reference}`
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  function handleShare() {
    if (!content) return
    const text = `"${content.verse_of_the_day.text}" — ${content.verse_of_the_day.reference}`
    if (navigator.share) {
      navigator.share({
        title: `${content.verse_of_the_day.reference} | Bible Verse of the Day`,
        text: `${text}\n\nRead daily verses and download wallpapers at ${window.location.origin}`,
      }).catch(() => {})
    } else {
      handleCopy()
    }
  }

  function toggleSpeech() {
    if (!content || !('speechSynthesis' in window)) return

    if (isPlaying) {
      window.speechSynthesis.cancel()
      setIsPlaying(false)
      return
    }

    window.speechSynthesis.cancel()
    const utterance = new SpeechSynthesisUtterance(
      `${content.verse_of_the_day.reference}. ${content.verse_of_the_day.text}. Reflection: ${content.reflection.content}`
    )
    utterance.rate = 0.95
    utterance.onend = () => setIsPlaying(false)
    utterance.onerror = () => setIsPlaying(false)
    setIsPlaying(true)
    window.speechSynthesis.speak(utterance)
  }

  const jsonLd = content
    ? [websiteSchema(SITE_URL), dailyVerseSchema(content, `${SITE_URL}/`)]
    : [websiteSchema(SITE_URL)]

  // Curated showcase wallpapers available offline & instant
  const showcaseWallpapers: FeaturedWallpaper[] = [
    {
      id: 'today-daily',
      title: "Today's Sacred Verse",
      category: 'Daily Verse',
      url: heroBgUrl,
    },
    {
      id: 'share-1',
      title: 'Grace & Truth',
      category: 'Grace',
      url: `${BASE}images/bg_share_1.png`,
    },
    {
      id: 'share-2',
      title: 'Peace in Prayer',
      category: 'Prayer',
      url: `${BASE}images/bg_share_2.png`,
    },
    {
      id: 'share-3',
      title: 'Everlasting Hope',
      category: 'Hope',
      url: `${BASE}images/bg_share_3.png`,
    },
  ]

  return (
    <>
      <SEO
        title="Daily Bible Verse, Devotional Wallpapers & Reflection"
        description="Start your day with God's Word. Today's Bible verse, sacred wallpapers, audio devotional, reflection, daily prayer, and 180+ Scripture stories."
        canonical="/"
        jsonLd={jsonLd[0]}
      />

      <main id="main-content">
        {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            1. HERO — today's verse
            Uses a plain gradient scrim rather than a CSS `filter: brightness()`
            plus blurred glow layers. Filters force the compositor to re-rasterise
            a full-viewport image, delaying LCP; a static gradient composites once.
            `fetchPriority="high"` marks this as the LCP element.
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
        <section
          aria-labelledby="hero-title"
          className="relative isolate overflow-hidden bg-ink-950 on-dark"
        >
          <img
            src={heroBgUrl}
            alt=""
            aria-hidden="true"
            fetchPriority="high"
            decoding="async"
            className="absolute inset-0 w-full h-full object-cover object-center"
          />

          {/* Scrim: a single composited gradient, no filters */}
          <div
            aria-hidden="true"
            className="absolute inset-0 bg-gradient-to-b from-ink-950/80 via-ink-950/70 to-ink-950/90"
          />

          <div className="relative shell py-20 sm:py-24 lg:py-28 text-center">
            <div className="max-w-3xl mx-auto">
              <p className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-sm
                            border border-white/20 px-4 py-1.5 rounded-full text-xs font-semibold
                            uppercase tracking-eyebrow text-gold-200 mb-6">
                <Icon name="sparkle" className="w-3.5 h-3.5" />
                <time dateTime={today}>
                  {new Date().toLocaleDateString('en-US', {
                    weekday: 'long',
                    month: 'long',
                    day: 'numeric',
                    year: 'numeric',
                  })}
                </time>
              </p>

              <h1
                id="hero-title"
                className="font-serif text-3xl sm:text-4xl lg:text-5xl font-bold
                           tracking-tight text-white leading-tight mb-6"
              >
                Bible Verse of the Day
              </h1>

              {loading ? (
                <div className="animate-pulse space-y-3 max-w-xl mx-auto mt-4" aria-hidden="true">
                  <div className="h-5 bg-white/20 rounded-full w-3/4 mx-auto" />
                  <div className="h-5 bg-white/20 rounded-full w-full mx-auto" />
                  <div className="h-5 bg-white/20 rounded-full w-2/3 mx-auto" />
                </div>
              ) : content ? (
                <div className="space-y-5 animate-slide-up">
                  <blockquote className="max-w-2xl mx-auto">
                    <p className="font-serif text-xl sm:text-2xl lg:text-[28px] italic
                                  leading-[1.5] text-white text-balance">
                      &ldquo;{content.verse_of_the_day.text}&rdquo;
                    </p>
                    <p className="mt-5 inline-block bg-gold-500/20 border border-gold-400/40
                                  text-gold-200 font-semibold text-sm sm:text-base px-4 py-1.5
                                  rounded-full tracking-wide">
                      {content.verse_of_the_day.reference}
                    </p>
                  </blockquote>

                  {/* Quick actions */}
                  <div className="flex flex-wrap items-center justify-center gap-2 pt-2">
                    {'speechSynthesis' in window && (
                      <button
                        type="button"
                        onClick={toggleSpeech}
                        aria-pressed={isPlaying}
                        className={`inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl
                                    text-xs sm:text-sm font-semibold border transition-colors ${
                                      isPlaying
                                        ? 'bg-gold-500 text-ink-950 border-gold-400'
                                        : 'bg-white/10 hover:bg-white/20 text-white border-white/20'
                                    }`}
                      >
                        <Icon name={isPlaying ? 'stop' : 'volume'} className="w-4 h-4" />
                        <span>{isPlaying ? 'Stop' : 'Listen'}</span>
                      </button>
                    )}

                    <button
                      type="button"
                      onClick={handleCopy}
                      className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl
                                 text-xs sm:text-sm font-semibold bg-white/10 hover:bg-white/20
                                 text-white border border-white/20 transition-colors"
                    >
                      <Icon name={copied ? 'check' : 'copy'} className="w-4 h-4" />
                      <span>{copied ? 'Copied' : 'Copy'}</span>
                    </button>

                    <button
                      type="button"
                      onClick={handleShare}
                      className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl
                                 text-xs sm:text-sm font-semibold bg-white/10 hover:bg-white/20
                                 text-white border border-white/20 transition-colors"
                    >
                      <Icon name="share" className="w-4 h-4" />
                      <span>Share</span>
                    </button>

                    <button
                      type="button"
                      onClick={() => setLightboxImage(heroBgUrl)}
                      className="inline-flex items-center gap-1.5 px-4 py-2.5 rounded-xl
                                 text-xs sm:text-sm font-bold bg-gold-500 hover:bg-gold-400
                                 text-ink-950 transition-colors"
                    >
                      <Icon name="image" className="w-4 h-4" />
                      <span>Wallpaper</span>
                    </button>
                  </div>
                </div>
              ) : (
                <p className="text-parchment-200 mt-4">
                  No verse available for today.{' '}
                  <Link to="/archive" className="underline underline-offset-4">
                    Browse the archive
                  </Link>
                  .
                </p>
              )}
            </div>
          </div>
        </section>

        {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            2. TODAY'S DEVOTIONAL
            Overlaps the hero slightly so the card feels seated, not stacked.
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
        <section className="shell-narrow -mt-12 sm:-mt-16 relative z-20 mb-16" aria-label="Daily devotional">
          {loading ? (
            <VerseCardSkeleton />
          ) : content ? (
            <VerseCard content={content} isToday />
          ) : (
            <div className="card p-8 text-center text-ink-600">
              <p>No devotional content found for today.</p>
              <Link to="/archive" className="btn-primary mt-4 mx-auto w-fit">
                Browse Verse Archive
              </Link>
            </div>
          )}
        </section>

        {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            3. FEATURED SCRIPTURE WALLPAPERS
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
        <section className="shell mb-16" aria-labelledby="wallpapers-title">
          <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3 mb-6">
            <div>
              <p className="eyebrow">
                <Icon name="image" className="w-3.5 h-3.5" />
                Wallpapers &amp; Devotional Art
              </p>
              <h2 id="wallpapers-title" className="section-title">
                Sacred Scripture Wallpapers
              </h2>
              <p className="text-ink-600 text-sm mt-1 max-w-prose">
                Inspiring devotional backgrounds and phone wallpapers from daily
                verses and sacred themes.
              </p>
            </div>
            <Link
              to="/community"
              className="text-sm font-semibold text-gold-800 hover:text-gold-900
                         inline-flex items-center gap-1 shrink-0"
            >
              Explore all <Icon name="arrowRight" className="w-4 h-4" />
            </Link>
          </div>

          <ul className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {showcaseWallpapers.map(wp => (
              <li key={wp.id}>
                <button
                  type="button"
                  onClick={() => setLightboxImage(wp.url)}
                  className="group relative block w-full overflow-hidden rounded-2xl
                             bg-ink-900 border border-parchment-200 aspect-[3/4] text-left
                             transition-shadow hover:shadow-lift"
                >
                  <img
                    src={wp.url}
                    alt={`${wp.title} — ${wp.category} Bible verse wallpaper`}
                    loading="lazy"
                    decoding="async"
                    className="absolute inset-0 w-full h-full object-cover
                               transition-transform duration-500 ease-out group-hover:scale-105"
                  />
                  <span
                    aria-hidden="true"
                    className="absolute inset-0 bg-gradient-to-t from-ink-950/90 via-ink-950/20 to-transparent"
                  />
                  <span className="absolute bottom-0 inset-x-0 p-3 flex items-end justify-between gap-2">
                    <span className="min-w-0">
                      <span className="inline-block text-[10px] font-bold uppercase tracking-wider
                                       bg-gold-500 text-ink-950 px-2 py-0.5 rounded-full mb-1">
                        {wp.category}
                      </span>
                      <span className="block font-serif font-semibold text-sm text-white line-clamp-1">
                        {wp.title}
                      </span>
                    </span>
                    <span className="shrink-0 grid place-items-center w-8 h-8 rounded-full
                                     bg-white/20 text-white backdrop-blur-md
                                     group-hover:bg-gold-500 group-hover:text-ink-950 transition-colors">
                      <Icon name="download" className="w-4 h-4" />
                    </span>
                  </span>
                </button>
              </li>
            ))}
          </ul>

          {/* Category chips */}
          <ul className="mt-5 flex gap-2 overflow-x-auto no-scrollbar -mx-4 px-4 sm:mx-0 sm:px-0">
            {['Faith', 'Grace', 'Hope', 'Love', 'Peace', 'Praise', 'Prayer', 'Strength'].map(cat => (
              <li key={cat} className="shrink-0">
                <Link
                  to="/community"
                  className="inline-block text-xs font-semibold px-3 py-1.5 rounded-full
                             bg-white text-gold-900 border border-gold-200
                             hover:bg-gold-600 hover:text-white hover:border-gold-600 transition-colors"
                >
                  {cat}
                </Link>
              </li>
            ))}
            <li className="shrink-0">
              <Link
                to="/archive"
                className="inline-flex items-center gap-1.5 text-xs font-semibold px-3 py-1.5
                           rounded-full bg-ink-800 text-white hover:bg-ink-900 transition-colors"
              >
                <Icon name="archive" className="w-3.5 h-3.5" />
                Past daily verses
              </Link>
            </li>
          </ul>
        </section>

        {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            4. QUICK ACCESS DESTINATIONS
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
        <section className="shell mb-16" aria-labelledby="explore-title">
          <h2 id="explore-title" className="sr-only">
            Explore the app
          </h2>
          <ul className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {([
              { to: '/archive',   icon: 'archive', label: 'Verse Archive', desc: 'Past daily verses' },
              { to: '/community', icon: 'image',   label: 'HD Wallpapers',  desc: 'Themed scripture art' },
              { to: '/stories',   icon: 'book',    label: '180+ Stories',   desc: 'Old & New Testament' },
              { to: '/bible',     icon: 'bible',   label: 'Bible Reader',   desc: 'All 66 sacred books' },
            ] satisfies { to: string; icon: IconName; label: string; desc: string }[]).map(
              ({ to, icon, label, desc }) => (
              <li key={to}>
                <Link
                  to={to}
                  className="card group flex flex-col items-center text-center p-5 h-full
                             hover:shadow-lift hover:border-gold-300 transition-all duration-200"
                >
                  <span
                    aria-hidden="true"
                    className="grid place-items-center w-12 h-12 rounded-full bg-gold-50
                               text-gold-700 mb-3 group-hover:bg-gold-100 transition-colors"
                  >
                    <Icon name={icon} className="w-6 h-6" />
                  </span>
                  <span className="font-semibold text-sm text-ink-900">{label}</span>
                  <span className="text-xs text-ink-500 mt-1">{desc}</span>
                </Link>
              </li>
            ))}
          </ul>
        </section>

        {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            5. FEATURED BIBLE STORIES
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
        <section className="shell mb-16" aria-labelledby="stories-title">
          <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3 mb-6">
            <div>
              <p className="eyebrow">
                <Icon name="book" className="w-3.5 h-3.5" />
                Scripture Narratives
              </p>
              <h2 id="stories-title" className="section-title">
                Bible Stories &amp; Narratives
              </h2>
            </div>
            <Link
              to="/stories"
              className="text-sm font-semibold text-gold-800 hover:text-gold-900
                         inline-flex items-center gap-1 shrink-0"
            >
              Browse all 180+ <Icon name="arrowRight" className="w-4 h-4" />
            </Link>
          </div>

          <ul className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {storiesLoading
              ? Array.from({ length: 6 }).map((_, i) => (
                  <li key={i}><StoryCardSkeleton /></li>
                ))
              : featuredStories.map(story => (
                  <li key={story.id}><StoryCard story={story} /></li>
                ))}
          </ul>
        </section>

        {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            6. SPIRITUAL SPOTLIGHT: PRAYER & TEACHING
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
        <section className="shell mb-16" aria-labelledby="spotlight-title">
          <h2 id="spotlight-title" className="sr-only">
            Prayer and teaching
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Daily prayer */}
            <article className="relative overflow-hidden rounded-2xl bg-ink-900 text-white
                                p-6 sm:p-8 flex flex-col justify-between min-h-[260px] on-dark group">
              <img
                src={`${BASE}images/bg_share_2.png`}
                alt=""
                aria-hidden="true"
                loading="lazy"
                decoding="async"
                className="absolute inset-0 w-full h-full object-cover opacity-30
                           group-hover:scale-105 transition-transform duration-500"
              />
              <div aria-hidden="true"
                className="absolute inset-0 bg-gradient-to-t from-ink-950 via-ink-950/75 to-ink-900/60" />

              <div className="relative">
                <p className="inline-flex items-center gap-1.5 bg-white/15 border border-white/20
                              px-3 py-1 rounded-full text-[11px] font-semibold tracking-eyebrow
                              uppercase text-gold-200 mb-3">
                  <Icon name="prayer" className="w-3.5 h-3.5" />
                  Daily Prayer Focus
                </p>
                <h3 className="font-serif text-2xl font-semibold mb-2">
                  A Prayer for Peace &amp; Guidance
                </h3>
                <p className="text-sm text-parchment-200 line-clamp-3 leading-relaxed font-serif italic">
                  &ldquo;Lord, grant me the serenity to accept what I cannot change, courage
                  to change the things I can, and wisdom to know the difference. Walk with me
                  today and guard my heart.&rdquo;
                </p>
              </div>

              <Link
                to="/prayers"
                className="relative mt-4 inline-flex items-center gap-1.5 text-xs font-bold
                           text-gold-200 hover:text-white uppercase tracking-eyebrow"
              >
                Explore all prayers <Icon name="arrowRight" className="w-3.5 h-3.5" />
              </Link>
            </article>

            {/* Teachings of Jesus */}
            <article className="relative overflow-hidden rounded-2xl bg-ink-900 text-white
                                p-6 sm:p-8 flex flex-col justify-between min-h-[260px] on-dark group">
              <img
                src={`${BASE}images/bg_share_3.png`}
                alt=""
                aria-hidden="true"
                loading="lazy"
                decoding="async"
                className="absolute inset-0 w-full h-full object-cover opacity-30
                           group-hover:scale-105 transition-transform duration-500"
              />
              <div aria-hidden="true"
                className="absolute inset-0 bg-gradient-to-t from-ink-950 via-ink-950/75 to-ink-900/60" />

              <div className="relative">
                <p className="inline-flex items-center gap-1.5 bg-white/15 border border-white/20
                              px-3 py-1 rounded-full text-[11px] font-semibold tracking-eyebrow
                              uppercase text-gold-200 mb-3">
                  <Icon name="bible" className="w-3.5 h-3.5" />
                  Words of Jesus Christ
                </p>
                <h3 className="font-serif text-2xl font-semibold mb-2">
                  The Sermon on the Mount
                </h3>
                <p className="text-sm text-parchment-200 line-clamp-3 leading-relaxed font-serif italic">
                  &ldquo;Blessed are the pure in heart, for they will see God. Blessed are the
                  peacemakers, for they will be called children of God.&rdquo;
                  <span className="not-italic text-gold-200"> &mdash; Matthew 5:8-9</span>
                </p>
              </div>

              <Link
                to="/teachings"
                className="relative mt-4 inline-flex items-center gap-1.5 text-xs font-bold
                           text-gold-200 hover:text-white uppercase tracking-eyebrow"
              >
                Read Jesus' teachings <Icon name="arrowRight" className="w-3.5 h-3.5" />
              </Link>
            </article>
          </div>
        </section>

        {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
            7. MOBILE APP & WIDGET SHOWCASE
        ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
        <section className="shell mb-16" aria-labelledby="app-title">
          <div className="relative overflow-hidden rounded-3xl bg-ink-900 text-white
                          p-6 sm:p-10 border border-ink-800 on-dark">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-center">
              <div>
                <p className="inline-flex items-center gap-1.5 bg-gold-500/15 text-gold-200
                              border border-gold-400/30 px-3 py-1 rounded-full text-[11px]
                              font-bold uppercase tracking-eyebrow mb-4">
                  <Icon name="download" className="w-3.5 h-3.5" />
                  Mobile &amp; Desktop Experience
                </p>
                <h2 id="app-title" className="font-serif text-3xl sm:text-4xl font-semibold mb-4 leading-tight">
                  Take God's Word With You Everywhere
                </h2>
                <p className="text-parchment-200 text-sm sm:text-base leading-relaxed mb-6 max-w-prose">
                  Enjoy daily lockscreen and home screen widgets, seamless offline scripture
                  reading, custom verse wallpapers, and uplifting devotionals every morning.
                </p>

                <div className="flex flex-wrap items-center gap-3">
                  <a
                    href="https://play.google.com/store/apps/details?id=com.bible.verseoftheday2026"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="inline-flex items-center gap-2 bg-gold-500 hover:bg-gold-400
                               text-ink-950 font-bold px-5 py-3 rounded-xl transition-colors"
                  >
                    <Icon name="download" className="w-4 h-4" />
                    <span>Download on Google Play</span>
                  </a>
                  <Link
                    to="/community"
                    className="inline-flex items-center gap-2 bg-white/10 hover:bg-white/20
                               text-white font-semibold px-5 py-3 rounded-xl
                               border border-white/20 transition-colors"
                  >
                    <Icon name="image" className="w-4 h-4" />
                    <span>Explore Wallpapers</span>
                  </Link>
                </div>
              </div>

              {/* Widget preview */}
              <div className="flex justify-center">
                <div className="relative rounded-2xl overflow-hidden shadow-lift
                                border-4 border-white/15 max-w-[300px] group">
                  <img
                    src={`${BASE}images/widget_preview.jpeg`}
                    alt="Bible Verse of the Day app showing a lock screen widget and home screen widget with the daily verse"
                    width={600}
                    height={1200}
                    loading="lazy"
                    decoding="async"
                    className="w-full h-auto object-cover group-hover:scale-105 transition-transform duration-500"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
          LIGHTBOX — wallpaper preview & download
          A real modal: labelled, Escape-closable, scroll-locked, and it
          restores focus to whatever opened it.
      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ */}
      {lightboxImage && (
        <div
          role="dialog"
          aria-modal="true"
          aria-label="Wallpaper preview"
          className="fixed inset-0 z-50 bg-ink-950/95 backdrop-blur-sm flex flex-col
                     items-center justify-between p-4 sm:p-8 animate-fade-in on-dark"
          onClick={() => setLightboxImage(null)}
        >
          <div className="w-full flex justify-between items-center gap-4 max-w-4xl text-white">
            <p className="inline-flex items-center gap-1.5 text-xs uppercase tracking-eyebrow text-gold-200 font-semibold">
              <Icon name="image" className="w-4 h-4" />
              Sacred Wallpaper Preview
            </p>
            <button
              type="button"
              onClick={() => setLightboxImage(null)}
              className="grid place-items-center w-11 h-11 -mr-2 rounded-lg text-white
                         hover:bg-white/15 transition-colors"
              aria-label="Close wallpaper preview"
            >
              <Icon name="close" className="w-6 h-6" />
            </button>
          </div>

          <div
            className="flex-1 flex items-center justify-center max-w-4xl max-h-[70vh] my-4"
            onClick={e => e.stopPropagation()}
          >
            <img
              src={lightboxImage}
              alt="Full size Bible verse wallpaper preview"
              className="max-h-full max-w-full object-contain rounded-xl shadow-lift"
            />
          </div>

          <div className="flex flex-wrap items-center justify-center gap-3" onClick={e => e.stopPropagation()}>
            <a
              href={lightboxImage}
              download="sacred-bible-wallpaper.webp"
              target="_blank"
              rel="noreferrer"
              className="btn-gold text-sm"
            >
              <Icon name="download" className="w-4 h-4" />
              Download free HD wallpaper
            </a>
            <button
              type="button"
              onClick={() => setLightboxImage(null)}
              className="px-5 py-2.5 rounded-xl border border-white/25 bg-white/10
                         text-white text-sm font-medium hover:bg-white/20 transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      )}
    </>
  )
}
